[package]
name = "basic-frame-of-reference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Addresses memory by bits, for packed collections and bitfields
bitvec = "1.0.1"

